name: Make_Release
on: 
  workflow_dispatch:

jobs:
  build:
    name: Build os
    runs-on: ubuntu-20.04
    steps:
      - name: Maximize disk space
        uses: easimon/maximize-build-space@master
        with:
          swap-size-mb: 1524
          remove-dotnet: 'true'
          remove-android: 'true'

      - name: Build
        run: |
           sudo apt install git
           git clone "https://github.com/cat-master21/RRR-builder.git" && cd ./RRR-builder
           chmod +x ./CI.sh
           sudo bash ./CI.sh
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "continuous-generic"
          prerelease: false
          title: "Rolling Rhino generic release"
          files: rolling-rhino-$(date -I).iso
