name: Make_Release
on: workflow_dispatch

jobs:
  build:
    name: Build OS
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Build
        run: |
         sudo rm -rf /usr/local/lib/android
         sudo rm -rf /usr/share/dotnet
         sudo rm -rf /opt/ghc
         sudo rm -rf "/usr/local/share/boost"
         sudo rm -rf "$AGENT_TOOLSDIRECTORY"
         sudo apt-get install xorriso coreutils squashfs-tools cd-boot-images git axel -y
         cd ~/
         sudo git clone -b master "https://github.com/rollingrhinoremix/RRR-builder.git" && cd ./RRR-builder
         sudo chmod +x ./fetch_build ./build/build.sh ./build/switch.sh
         sudo ./fetch_build
         sudo rm -rf ./ubuntu.iso
         sudo find . -maxdepth 1 ! \( -name "*.iso*" -o -name '.' -o -name '..' \) -exec sudo rm -rf {} \;
      - uses: actions/upload-artifact@v3.0.0
        with:
          name: "rolling-rhino"
          path: ~/RRR-builder/
          retention-days: 3
          if-no-files-found: error
