name: Make_Release
on: 
  workflow_dispatch:

jobs:
  build:
    name: Build OS
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
         sudo rm -rf /usr/local/lib/android
         sudo rm -rf /usr/share/dotnet
         sudo rm -rf /opt/ghc
         sudo rm -rf "/usr/local/share/boost"
         sudo rm -rf "$AGENT_TOOLSDIRECTORY"
         sudo apt-get update -y
         sudo apt-get dist-upgrade
         sudo apt-get install xorriso coreutils squashfs-tools git -y
         wget "http://mirrors.kernel.org/ubuntu/pool/main/c/cd-boot-images-amd64/cd-boot-images-amd64_17_all.deb"
         sudo dpkg -i "cd-boot-images-amd64_17_all.deb"
         rm -rf "./cd-boot-images-amd64_17_all.deb"
         sudo git clone "https://github.com/cat-master21/RRR-builder.git" && cd ./RRR-builder
         sudo chmod +x ./fetch_build ./build/build.sh ./build/switch.sh
         sudo ./fetch_build
         sudo df -h
         sudo rm -rf ./ubuntu.iso
      - uses: "marvinpinto/action-automatic-releases@1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "continuous-generic"
          prerelease: false
          title: "Rolling Rhino generic release"
          files: rolling-rhino-$(date -I).iso
