name: Make_Release
on: 
  workflow_dispatch:

jobs:
  build:
    name: Build os
    runs-on: ubuntu-20.04
    steps:
      - name: Build
        run: |
         sudo apt-get update -y
         sudo apt-get dist-upgrade
         sudo apt-get install axel xorriso coreutils squashfs-tools -y
         wget "http://mirrors.kernel.org/ubuntu/pool/main/c/cd-boot-images-amd64/cd-boot-images-amd64_17_all.deb"
         sudo dpkg -i "cd-boot-images-amd64_17_all.deb"
         rm -rf "./cd-boot-images-amd64_17_all.deb"
         source fetch_build.conf && axel "DOWNLOAD_ISO" --output="ubuntu.iso"
         chmod +x ./build/build.sh ./build/switch.sh
         sudo df -h
         sudo make build.iso
         rm -rf ./ubuntu.iso
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "continuous-generic"
          prerelease: false
          title: "Rolling Rhino generic release"
          files: rolling-rhino-$(date -I).iso
